name: Test Modules
permissions:
  id-token: write
  contents: write
  checks: write
  security-events: write
  actions: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      AWS_REGION:
        description: "AWS Region"
        required: true
        default: "us-east-1"
      AWS_ACCESS_KEY_ID:
        required: true
        type: string
      AWS_SECRET_ACCESS_KEY:
        required: true
        type: string
      AWS_SESSION_TOKEN:
        required: false
        type: string

env:
  AWS_REGION: ${{ inputs.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ inputs.AWS_SESSION_TOKEN }}

concurrency:
  group: ${{ github.workflow }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get services
        id: get-services
        run: |
          result='["vpc"]'
          #result='["vpc","acm","apigateway","autoscaling","cloudmap","cloudfront","logs","docdb","dynamodb","ec2","ecr","ecs","eks","elbv2","elasticache_redis","elasticbeanstalk","guardduty","iam","kms","aws_lambda","rds","s3","sns","sqs","wafv2","stepfunction","msk","aurora","security_group","vpc_endpoint","vpn_client","elasticsearch"]'
          services=$(echo "$result" | jq -c '.')
          echo "services=$services" >> $GITHUB_OUTPUT

    outputs:
      services: ${{ steps.get-services.outputs.services }}

  generate_tf_code:
    needs: [setup]
    if: needs.setup.outputs.services != '[]'
    name: ${{ matrix.service }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: ${{fromJson(needs.setup.outputs.services)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Generate TF files for ${{ matrix.service }}
        run: |
          # get the aws_account id using sts and put in a variiable called aws_account_id
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          # run the python script main.py aws_account_id aws_region service_name but need to install the python requirements.txt first
          pip install -r requirements.txt
          python main.py $AWS_ACCOUNT_ID ${{ env.AWS_REGION }} ${{ matrix.service }}

        #   docker run -v /tmp/generated:/app/generated -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN -e AWS_REGION=$AWS_REGION public.ecr.aws/u5n7c4j1/ft-terraformer:latest main.py ${AWS_ACCOUNT_ID} ${{ env.AWS_REGION }} ${{ matrix.service }}
